server:
  port: 9001  servlet:    session:      cookie:        name: OAUTH2SESSION
spring:
  application:
    name: demo-sso-client1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
security:  oauth2:    client:      client-id: client_1
      client-secret: 123456
      user-authorization-uri: http://localhost:9901/oauth/authorize
      access-token-uri: http://localhost:9901/oauth/token
    resource:
      jwt:        key-uri: http://localhost:9901/oauth/token_key