server:
  port: 9901
spring:
  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.125.133:3306/oauth2
    username: root
    password: Welcome1       
  application:
    name: demo-sso-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848